# -*- coding: utf-8 -*-
"""task3_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlIK5u1y5WxLqDtClzmtAsVobkDayf_a
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load the dataset
df = pd.read_csv('/content/churnguard_clean.csv')

# Display the first few rows to understand the data
print("Original DataFrame head:")
display(df.head())

# Display data types and missing values
print("\nDataFrame Info:")
df.info()

"""### Target Variable Encoding

Encode the 'Churn' column: 'Yes' to 1, 'No' to 0.
"""

# Encode the 'Churn' column
# Clean the 'Churn' column first: strip whitespace and convert to lowercase for robust mapping
df['Churn'] = df['Churn'].astype(str).str.strip().str.lower().map({'yes': 1, 'no': 0})

# Drop rows where 'Churn' might still be NaN (due to unexpected values in original data that weren't 'yes' or 'no')
df.dropna(subset=['Churn'], inplace=True)

# Convert 'Churn' to integer type, as it now contains only 0s and 1s
df['Churn'] = df['Churn'].astype(int)

print("\nDataFrame head after Churn encoding and NaN removal:")
display(df.head())

"""### One-Hot Encoding for Categorical Variables

Perform one-hot encoding on the specified categorical variables using `pd.get_dummies` with `drop_first=True`.
"""

# Required categorical variables for one-hot encoding
categorical_cols = ['gender', 'PhoneService', 'InternetService', 'Contract', 'PaperlessBilling', 'PaymentMethod']

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("\nDataFrame head after one-hot encoding:")
display(df_encoded.head())

print("\nEncoded DataFrame columns:")
print(df_encoded.columns.tolist())

"""### Splitting Data into Features (X) and Target (y)

Define `X` (all columns except Churn) and `y` (Churn).
"""

# Define X and y
X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

"""### Train/Test Split

Split the data into training and testing sets (80/20, `random_state=42`).
"""

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### Train Logistic Regression Model

Train a Logistic Regression model with `max_iter=1000`.
"""

# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

"""### Evaluate Model Performance

Print the test accuracy and the classification report with target names 'Stay' and 'Churn'.
"""

# Make predictions on the test set
y_pred = model.predict(X_test)

# Print test accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Stay', 'Churn']))

# Save the test accuracy and classification report to a file
report_filename = 'logistic_regression_report.txt'
with open(report_filename, 'w') as f:
    f.write(f"Test Accuracy: {accuracy:.4f}\n\n")
    f.write("Classification Report:\n")
    f.write(classification_report(y_test, y_pred, target_names=['Stay', 'Churn']))

print(f"Logistic Regression report saved to {report_filename}")

import joblib

# Define filenames for the model and feature columns
model_filename = 'churn_prediction_model.pkl'
feature_columns_filename = 'churn_prediction_features.pkl'

# Save the trained model
joblib.dump(model, model_filename)
print(f"Trained Logistic Regression model saved to {model_filename}")

# Save the column names (features) used for training
# This is crucial for ensuring new data is preprocessed with the same columns and order
joblib.dump(X.columns.tolist(), feature_columns_filename)
print(f"Feature columns list saved to {feature_columns_filename}")