# -*- coding: utf-8 -*-
"""task2_clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ml07tme35v3XkTtSXI4KrCoRSNv8Me_f
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/churnguard_data.csv')
display(df.head())

"""### Data Cleaning Steps"""

# Drop 'customerID'
if 'customerID' in df.columns:
    df = df.drop(columns=['customerID'])
    print("Dropped 'customerID' column.")
else:
    print("'customerID' column not found.")

# Remove duplicate rows
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
print(f"Removed {initial_rows - df.shape[0]} duplicate rows.")

# Strip whitespace from 'gender' and 'PaymentMethod'

for col in ['gender', 'PaymentMethod']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()
        print(f"Whitespace stripped from '{col}'.")
    else:
        print(f"'{col}' column not found.")

# Standardise casing for 'Churn', 'PhoneService', and 'PaperlessBilling'
for col in ['Churn', 'PhoneService', 'PaperlessBilling']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.lower()
        print(f"Casing standardized to lowercase for '{col}'.")
    else:
        print(f"'{col}' column not found.")

# Map 'Contract' variations
contract_mapping = {
    'month-to-month': 'Month-to-month',
    'one year': 'One year',
    'two year': 'Two year'
}
if 'Contract' in df.columns:
    df['Contract'] = df['Contract'].astype(str).str.lower().replace(contract_mapping)
    print("Mapped 'Contract' variations.")
    print(df['Contract'].value_counts())
else:
    print("'Contract' column not found.")

# Map 'InternetService' variations
internet_service_mapping = {
    'dsl': 'DSL',
    'fiber optic': 'Fiber optic',
    'no': 'No'
}
if 'InternetService' in df.columns:
    df['InternetService'] = df['InternetService'].astype(str).str.lower().replace(internet_service_mapping)
    print("Mapped 'InternetService' variations.")
    print(df['InternetService'].value_counts())
else:
    print("'InternetService' column not found.")

# Convert 'TotalCharges' to numeric with errors="coerce"
if 'TotalCharges' in df.columns:
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    print("Converted 'TotalCharges' to numeric.")
else:
    print("'TotalCharges' column not found.")

# Remove 'tenure' <= 0
if 'tenure' in df.columns:
    initial_tenure_rows = df.shape[0]
    df = df[df['tenure'] > 0]
    print(f"Removed {initial_tenure_rows - df.shape[0]} rows where 'tenure' was <= 0.")
else:
    print("'tenure' column not found.")

# Remove 'MonthlyCharges' < 10 or 'MonthlyCharges' > 200
if 'MonthlyCharges' in df.columns:
    initial_monthly_charges_rows = df.shape[0]
    df = df[(df['MonthlyCharges'] >= 10) & (df['MonthlyCharges'] <= 200)]
    print(f"Removed {initial_monthly_charges_rows - df.shape[0]} rows based on 'MonthlyCharges' range.")
else:
    print("'MonthlyCharges' column not found.")

# Fill missing values

if 'MonthlyCharges' in df.columns and df['MonthlyCharges'].isnull().any():
    mean_monthly_charges = df['MonthlyCharges'].mean()
    df['MonthlyCharges'].fillna(mean_monthly_charges, inplace=True)
    print(f"Filled missing 'MonthlyCharges' with mean: {mean_monthly_charges:.2f}.")

if 'TotalCharges' in df.columns and df['TotalCharges'].isnull().any():
    mean_total_charges = df['TotalCharges'].mean()
    df['TotalCharges'].fillna(mean_total_charges, inplace=True)
    print(f"Filled missing 'TotalCharges' with mean: {mean_total_charges:.2f}.")

if 'tenure' in df.columns and df['tenure'].isnull().any():
    median_tenure = df['tenure'].median()
    df['tenure'].fillna(round(median_tenure), inplace=True)
    print(f"Filled missing 'tenure' with rounded median: {round(median_tenure)}.")

# Print final shape and missing-value counts
print("\nFinal DataFrame Shape:", df.shape)
print("\nMissing values after cleaning:\n", df.isnull().sum())

# Save the cleaned DataFrame to a new CSV file
df.to_csv('/content/churnguard_clean.csv', index=False)
print("Cleaned data saved to 'churnguard_clean.csv'")