# -*- coding: utf-8 -*-
"""task4_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ualt_hEuDE6U9tYHYeYk_WwMAsahAksW

### Churn Prediction Script

This script will take specific user inputs and use a pre-trained model to predict whether a customer is likely to churn or stay.
"""

import pandas as pd
import joblib

# --- Loading your trained model and feature names---
# The user has provided 'churn_prediction_model.pkl' and 'churn_prediction_features.pkl'.

try:
    model = joblib.load('/content/churn_prediction_model.pkl')
    expected_features = joblib.load('/content/churn_prediction_features.pkl') # Load the expected feature names
    print("SUCCESS: Churn prediction model and feature names loaded successfully.")

except FileNotFoundError as e:
    print(f"ERROR: One or more model files not found: {e}. Please ensure 'churn_prediction_model.pkl' and 'churn_prediction_features.pkl' exist in /content/.")
    print("Using a dummy prediction function for demonstration.")
    # Dummy model and features for demonstration if actual files are not found
    class DummyModel:
        def predict(self, X):
            predictions = []
            for _, row in X.iterrows():
                if row['total_charges'] < 500 and row['tenure'] < 10 and row['monthly_charges'] > 50:
                    predictions.append(1) # Churn
                else:
                    predictions.append(0) # Stay
            return predictions
    model = DummyModel()
    expected_features = ['tenure', 'monthly_charges', 'total_charges', 'senior_citizen', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year']

except Exception as e:
    print(f"An error occurred while loading the model or features: {e}")
    print("Using a dummy prediction function for demonstration.")
    class DummyModel:
        def predict(self, X):
            predictions = []
            for _, row in X.iterrows():
                if row['total_charges'] < 500 and row['tenure'] < 10 and row['monthly_charges'] > 50:
                    predictions.append(1) # Churn
                else:
                    predictions.append(0) # Stay
            return predictions
    model = DummyModel()
    expected_features = ['tenure', 'monthly_charges', 'total_charges', 'senior_citizen', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year']

def get_user_inputs():
    """Collects user inputs for churn prediction."""
    print("\nPlease provide the following details for churn prediction:")

    while True:
        try:
            tenure = int(input("Tenure in months (e.g., 24): "))
            if tenure < 0: raise ValueError
            break
        except ValueError:
            print("Invalid input. Please enter a non-negative integer for tenure.")

    while True:
        try:
            monthly_charges = float(input("Monthly Charges (e.g., 55.75): "))
            if monthly_charges < 0: raise ValueError
            break
        except ValueError:
            print("Invalid input. Please enter a non-negative number for monthly charges.")

    while True:
        try:
            total_charges_str = input("Total Charges (e.g., 1234.50, enter '0' if new customer): ")
            if total_charges_str.lower() == '0' and tenure > 0:
                print("Warning: Total Charges is 0 but Tenure is not 0. Assuming 0 for calculation.")
            total_charges = float(total_charges_str)
            if total_charges < 0: raise ValueError
            break
        except ValueError:
            print("Invalid input. Please enter a non-negative number for total charges.")

    while True:
        try:
            senior_citizen = int(input("Senior Citizen (1 for Yes, 0 for No): "))
            if senior_citizen not in [0, 1]: raise ValueError
            break
        except ValueError:
            print("Invalid input. Please enter 1 for Yes or 0 for No.")

    while True:
        try:
            contract = int(input("Contract type (0=Month-to-month, 1=One year, 2=Two year): "))
            if contract not in [0, 1, 2]: raise ValueError
            break
        except ValueError:
            print("Invalid input. Please enter 0, 1, or 2 for contract type.")

    return {
        'tenure': tenure,
        'monthly_charges': monthly_charges,
        'total_charges': total_charges,
        'senior_citizen': senior_citizen,
        'contract': contract
    }

def predict_churn(model, user_data, expected_features):
    """Makes a churn prediction using the loaded model, aligning features with expected_features."""

    # Create a DataFrame from the user input
    input_df = pd.DataFrame([user_data])

    # --- Apply One-Hot Encoding to 'contract' feature ---
    # Based on the problem description and error message, 'contract' needs OHE.
    # Create new columns for contract types and initialize to 0
    input_df['Contract_Month-to-month'] = 0
    input_df['Contract_One year'] = 0
    input_df['Contract_Two year'] = 0

    # Set the appropriate contract column to 1 based on user input
    if input_df['contract'].iloc[0] == 0:
        input_df['Contract_Month-to-month'] = 1
    elif input_df['contract'].iloc[0] == 1:
        input_df['Contract_One year'] = 1
    elif input_df['contract'].iloc[0] == 2:
        input_df['Contract_Two year'] = 1

    # Drop the original 'contract' column as it's now one-hot encoded
    input_df = input_df.drop(columns=['contract'])

    # --- Align features with the model's expected features ---
    # Add any missing expected features (e.g., if the model was trained with more features)
    # and ensure they are in the correct order.
    for feature in expected_features:
        if feature not in input_df.columns:
            input_df[feature] = 0 # Assume 0 for missing features, common for OHE

    # Reorder columns to match the order the model expects
    input_df = input_df[expected_features]

    # Make prediction
    prediction = model.predict(input_df)

    if prediction[0] == 1:
        return "Likely to CHURN"
    else:
        return "Likely to STAY"

# --- Run the prediction script ---
if __name__ == "__main__":
    user_inputs = get_user_inputs()
    print(f"\nUser Inputs: {user_inputs}")

    # Make sure the model object and expected_features are available from the previous cell
    if model is not None and expected_features is not None:
        result = predict_churn(model, user_inputs, expected_features)
        print(f"\nPrediction: {result}")
    else:
        print("Cannot make a prediction: Model or expected features were not loaded correctly. Please check the model path and loading code.")