# -*- coding: utf-8 -*-
"""task1_load_explore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYyXuYvjgfHZIUlHepgzP-qpn31ifH-S
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/churnguard_data.csv')

print('Dataset loaded successfully!')

"""### Dataset Shape"""

# Display the shape of the dataset
print(f"Dataset shape: {df.shape}")

"""### First Five Rows"""

# Display the first five rows
display(df.head())

"""### Column Names and Data Types"""

# Display column names and data types
df.info()

"""### Missing Values"""

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values > 0])

"""### Duplicate Rows"""

# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

"""### Value Counts for 'Churn'"""

# Value counts for the 'Churn' column
print("Value counts for 'Churn':")
display(df['Churn'].value_counts())

"""### Unique Values for 'Contract'"""

# Unique values for the 'Contract' column
print("Unique values for 'Contract':")
display(df['Contract'].unique())